name: catbreeds_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animate_do: ^3.0.2 # Animations
  dio: ^5.1.1 # Http requests
  flutter:
    sdk: flutter
  go_router: ^6.5.8 # Routing
  provider: ^6.0.5 # State management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/icons/